Repository Aniraj1/ProjectAdvisor, pull requests merged in 2023-07, with the labels that each got.

#11 Expenses income
  Pipfile
  Pipfile.lock
  backend/Expenses/PaginationFiles/cursorPagination.py
  backend/Expenses/models.py
  backend/Expenses/serializers.py
  backend/Expenses_Category/admin.py
  backend/Expenses_Category/migrations/0002_expensescategory_image.py
  backend/Expenses_Category/models.py
  backend/Expenses_Category/serializers.py
  backend/Expenses_Category/views.py
  backend/Income/models.py
  backend/Income/serializers.py
  backend/Income_Category/admin.py
  backend/Income_Category/migrations/0002_incomecategory_image.py
  backend/Income_Category/models.py
  backend/Income_Category/serializers.py
  backend/Income_Category/views.py
  backend/backend/settings.py
  backend/media/media/1.png
  backend/media/media/eight.jpg
  requirements.txt
Labels: enhancement

#12 Created a Core model that consists the API like, Category details, In…
  backend/Core/__init__.py
  backend/Core/admin.py
  backend/Core/apps.py
  backend/Core/contstants.py
  backend/Core/helpers.py
  backend/Core/migrations/__init__.py
  backend/Core/models.py
  backend/Core/tests.py
  backend/Core/urls.py
  backend/Core/views.py
  backend/Expenses/models.py
  backend/Income/models.py
  backend/backend/settings.py
  backend/backend/urls.py
  backend/media/media/Signature.jpg
  backend/media/media/Signature_BaEvwzI.jpg
  backend/media/media/Signature_qG45mGe.jpg
  backend/media/media/eleven.jpg
  backend/media/media/nine.jpg
  backend/media/media/ten.jpg
Labels: enhancement

#13 Worked with ImageUrls in Category Section
  backend/Expenses_Category/admin.py
  backend/Expenses_Category/migrations/0003_alter_expensescategory_image.py
  backend/Expenses_Category/migrations/0004_alter_expensescategory_image.py
  backend/Expenses_Category/models.py
  backend/Expenses_Category/views.py
  backend/Income/models.py
  backend/Income_Category/admin.py
  backend/Income_Category/models.py
  backend/Income_Category/views.py
  backend/backend/settings.py
  backend/backend/urls.py
  backend/media/media/1.png
  backend/media/media/Education.png
  backend/media/media/allowance.png
  backend/media/media/bill.png
  backend/media/media/dish.png
  backend/media/media/eight.jpg
  backend/media/media/eleven.jpg
  backend/media/media/five.jpg
  backend/media/media/four.jpg
  backend/media/media/gift.png
  backend/media/media/health.png
  backend/media/media/home.png
  backend/media/media/nine.jpg
  backend/media/media/others.png
  backend/media/media/passenger.png
  backend/media/media/salary.png
  backend/media/media/six.jpg
  backend/media/media/social.png
  backend/media/media/taxi.png
  backend/media/media/ten.jpg
  backend/media/media/tshirt.png
Labels: bug

#14 Created the views for fetching Income Category details as well as mad…
  backend/Core/urls.py
  backend/Core/views.py
Labels: enhancement

#15 Created Limit Model to set Limit for each category and compare your e…
  backend/Limit/__init__.py
  backend/Limit/admin.py
  backend/Limit/apps.py
  backend/Limit/migrations/0001_initial.py
  backend/Limit/migrations/0002_limit_created_date_limit_currency_limit_updated_date.py
  backend/Limit/migrations/0003_remove_limit_category_limit_and_more.py
  backend/Limit/migrations/0004_remove_limit_category_limits_and_more.py
  backend/Limit/migrations/0005_remove_limit_currency_alter_limit_created_date.py
  backend/Limit/migrations/__init__.py
  backend/Limit/models.py
  backend/Limit/serializers.py
  backend/Limit/tests.py
  backend/Limit/urls.py
  backend/Limit/views.py
  backend/backend/settings.py
  backend/backend/urls.py
Labels: enhancement

#16 Email
  backend/users/serializers.py
  backend/users/views.py
Labels: bug

#17 Merged the Master_2 branch with Subscription
  .DS_Store
Labels: bug, enhancement

#18 Todo list
  backend/Todo/PaginationFiles/cursorPagination.py
  backend/Todo/__init__.py
  backend/Todo/admin.py
  backend/Todo/apps.py
  backend/Todo/migrations/0001_initial.py
  backend/Todo/migrations/__init__.py
  backend/Todo/models.py
  backend/Todo/serializers.py
  backend/Todo/tests.py
  backend/Todo/urls.py
  backend/Todo/views.py
  backend/backend/settings.py
  backend/backend/urls.py
Labels: enhancement

#21 created_date and date column type from auto_now to auto_now_add
  backend/Expenses/migrations/0002_alter_expenses_created_date.py
  backend/Expenses/models.py
  backend/Expenses_Category/migrations/0005_alter_expensescategory_date.py
  backend/Expenses_Category/models.py
  backend/Income/migrations/0002_alter_income_created_date.py
  backend/Income/models.py
  backend/Income_Category/migrations/0003_alter_incomecategory_date.py
  backend/Income_Category/models.py
Labels: bug

#22 Solved the issue of not being able to log from the user when register…
  backend/users/urls.py
  backend/users/views.py
Labels: bug

#23 Make necessary changes and corrected overall and CategoryLimit view
  backend/Limit/views.py
Labels: bug

#24 Limit view
  backend/Limit/views.py
Labels: bug

#25 Made necessary changes in the Income and Expenses Category
  backend/Expenses_Category/models.py
  backend/Expenses_Category/views.py
  backend/Income_Category/models.py
  backend/Income_Category/views.py
  backend/backend/settings.py
Labels: bug
